# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Tag

# Model Form Field configuration
form: $/codecycler/toolbox/models/tag/fields.yaml

# Model Class name
modelClass: Codecycler\Toolbox\Models\Tag

# Default redirect location
defaultRedirect: codecycler/toolbox/tags

# Create page
create:
    title: Create Tag
    redirect: codecycler/toolbox/tags/update/:id
    redirectClose: codecycler/toolbox/tags

# Update page
update:
    title: Edit Tag
    redirect: codecycler/toolbox/tags
    redirectClose: codecycler/toolbox/tags

# Preview page
preview:
    title: Preview Tag
